[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lattice-bounds"
version = "0.1.0"
description = "Trying to use lattices to obtain lower bounds."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.0.0",
    "pandas>=2.0.0",
    "pulp>=2.16.0",
    "scipy>=1.13.0",
    "seaborn>=0.13.0",
    
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pylint",
    "black",
    "isort",
    "mypy",
    "ruff",
]

[tool.setuptools.packages.find]
where = ["src"]
